#pragma once
#include <es_fe/geom/algorithm.hpp>
#include <es_fe/geom/compare.hpp>
#include <es_fe/geom/geometry.hpp>
#include <es_fe/geom/linear_grid.hpp>
#include <es_fe/geom/linestring.hpp>
#include <es_fe/geom/point.hpp>
#include <es_fe/geom/points.hpp>
#include <es_fe/geom/polygon.hpp>
#include <es_fe/geom/rect.hpp>
//#include <es_fe/geom/segment.hpp>
