#pragma once
#include <es_fe/geometry/algorithm/area.hpp>
#include <es_fe/geometry/algorithm/bounding_rect.hpp>
#include <es_fe/geometry/algorithm/center.hpp>
#include <es_fe/geometry/algorithm/circumcentre.hpp>
#include <es_fe/geometry/algorithm/contains.hpp>
#include <es_fe/geometry/algorithm/distance.hpp>
#include <es_fe/geometry/algorithm/equals.hpp>
#include <es_fe/geometry/algorithm/length.hpp>
